---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
plot <- "https://openprescribing.net/api/1.0/org_location/?q=99H,P87003" %>% 
      sf::st_read() %>% 
      sf::st_as_sf()
```

```{r}
CCG_code <- "99H"

practicelist <- stringr::str_c("https://openprescribing.net/api/1.0/org_code/?&format=csv") %>%
    RCurl::getURL() %>%
    textConnection() %>%
    read.csv() %>%
    dplyr::filter(ccg == CCG_code)

practice_code <- paste(practicelist[,'id'],sep="", collapse=",")
variablesegment <- stringr::str_c("q=", CCG_code, ",", practice_code)

table1 <- stringr::str_c("https://openprescribing.net/api/1.0/org_location/?org_type=ccg&q=", CCG_code) %>% 
      sf::st_read() %>% 
      sf::st_as_sf() %>%
  dplyr::select(-ons_code) %>%
  dplyr::mutate(setting = NA)
 
table2 <- stringr::str_c("https://openprescribing.net/api/1.0/", "org_location/?", variablesegment) %>% 
      sf::st_read() %>% 
      sf::st_as_sf() %>%
  dplyr::mutate(org_type = "clinic")

rbind(table1, table2)
```

